# .coderabbit.yaml
language: ko-KR

reviews:
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - master
      - develop
      - feature/**
  profile: assertive

  # 리뷰 불필요 파일 제외 (아래는 예시)
  path_filters:
    - "!**/*.test.ts"
    - "!package-lock.json"